### ISSUE TITLE
The app doesn't start

### ISSUE THREAD

**Issue by dokasto** [anitacoder/nigerian-constitution-ai#3]
I just pulled the code now and ran `sh start.sh` nothing happens. How do you start the app? Can you update your readme with the right instructions.

**Comment by anitacoder** [comment]
done!

**Comment by dokasto** [comment]
@anitacoder the app still doesn't start for me, can you fix this

<img width="1153" height="331" alt="Image" src="https://github.com/user-attachments/assets/cd821b28-5a6b-4fc3-ab6b-eb25aa3ee306" />
